name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Stop the existing discord-bot.py process
      - name: Stop discord-bot.py
        run: |
          if(Get-Process -Name "python" | Where-Object { $_.Path -eq "C:\Bots\Bot_1\Scripts\discord-bot.py" }) { Get-Process -Name "python" | Where-Object { $_.Path -eq "C:\Bots\Bot_1\Scripts\discord-bot.py" } | Stop-Process } 

      # Copy the Scripts folder to C:\Bots\Bot_1\Scripts on the Windows server
      - name: Copy Scripts folder
        run: |
          Copy-Item -Path ${{ github.workspace }}/Scripts -Destination C:\Bots\Bot_1\Scripts -Recurse

      # Start the discord-bot.py process
      - name: Start discord-bot.py
        run: |
          Start-Process -FilePath "C:\Bots\Bot_1\Scripts\discord-bot.py" -WindowStyle Hidden
